# Generated by Django 6.0.2 on 2026-03-01 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ApiDynasty',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('did', models.IntegerField()),
                ('dname', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'api_dynasty',
            },
        ),
        migrations.CreateModel(
            name='ApiProvince',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=45)),
                ('sid', models.IntegerField()),
            ],
            options={
                'db_table': 'api_province',
            },
        ),
        migrations.CreateModel(
            name='ApiScenery',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sid', models.IntegerField()),
                ('pid', models.IntegerField()),
                ('did', models.IntegerField()),
                ('sname', models.CharField(max_length=45)),
                ('label', models.IntegerField()),
                ('introduction', models.CharField(max_length=1000)),
                ('category', models.IntegerField()),
            ],
            options={
                'db_table': 'api_scenery',
            },
        ),
        migrations.CreateModel(
            name='ArchDynasty',
            fields=[
                ('did', models.IntegerField(primary_key=True, serialize=False)),
                ('dname', models.CharField(max_length=45, verbose_name='朝代名称')),
                ('period', models.CharField(blank=True, max_length=100, verbose_name='时期')),
                ('description', models.TextField(blank=True, verbose_name='朝代简介')),
            ],
            options={
                'verbose_name': '朝代',
                'verbose_name_plural': '朝代',
                'db_table': 'architecture_dynasty',
            },
        ),
        migrations.CreateModel(
            name='ArchitecturalElement',
            fields=[
                ('eid', models.IntegerField(primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=100, verbose_name='元素名称')),
                ('category', models.CharField(max_length=50, verbose_name='类别')),
                ('original_text', models.TextField(blank=True, verbose_name='原文引用')),
                ('explanation', models.TextField(verbose_name='详细解释')),
                ('structure_description', models.TextField(blank=True, verbose_name='结构说明')),
                ('function_description', models.TextField(blank=True, verbose_name='功能说明')),
                ('evolution', models.TextField(blank=True, verbose_name='演变历史')),
                ('image_url', models.CharField(blank=True, max_length=500, verbose_name='示意图URL')),
                ('diagram_url', models.CharField(blank=True, max_length=500, verbose_name='结构图URL')),
            ],
            options={
                'verbose_name': '建筑元素',
                'verbose_name_plural': '建筑元素',
                'db_table': 'architecture_element',
            },
        ),
        migrations.CreateModel(
            name='ArchRegion',
            fields=[
                ('rid', models.IntegerField(primary_key=True, serialize=False)),
                ('rname', models.CharField(max_length=45, verbose_name='地域名称')),
                ('description', models.TextField(blank=True, verbose_name='地域特色')),
            ],
            options={
                'verbose_name': '地域',
                'verbose_name_plural': '地域',
                'db_table': 'architecture_region',
            },
        ),
        migrations.CreateModel(
            name='ArchStructureType',
            fields=[
                ('tid', models.IntegerField(primary_key=True, serialize=False)),
                ('tname', models.CharField(max_length=45, verbose_name='类型名称')),
                ('description', models.TextField(blank=True, verbose_name='类型描述')),
            ],
            options={
                'verbose_name': '结构类型',
                'verbose_name_plural': '结构类型',
                'db_table': 'architecture_structure_type',
            },
        ),
        migrations.CreateModel(
            name='ArchUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('like', models.CharField(blank=True, max_length=500, verbose_name='兴趣标签')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'architecture_users',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cid', models.IntegerField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('project_id', models.IntegerField(blank=True, null=True)),
                ('number', models.TextField(blank=True, null=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('introduction', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'details',
            },
        ),
        migrations.CreateModel(
            name='Dynasty',
            fields=[
                ('did', models.IntegerField(primary_key=True, serialize=False)),
                ('dname', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'dynasty',
            },
        ),
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('project_id', models.IntegerField(blank=True, null=True)),
                ('number', models.TextField(blank=True, null=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('dynasty', models.TextField(blank=True, null=True)),
                ('did', models.IntegerField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('public_time', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('district', models.TextField(blank=True, null=True)),
                ('pid', models.IntegerField(blank=True, null=True)),
                ('protection_department', models.TextField(blank=True, null=True)),
                ('origin', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'introduction',
            },
        ),
        migrations.CreateModel(
            name='key',
            fields=[
                ('kid', models.IntegerField(primary_key=True, serialize=False)),
                ('pname', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'key',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('pname', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'province',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('username', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('like', models.CharField(blank=True, max_length=12, null=True)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='AncientBuilding',
            fields=[
                ('bid', models.IntegerField(primary_key=True, serialize=False)),
                ('bname', models.CharField(max_length=100, verbose_name='建筑名称')),
                ('roof_type', models.CharField(blank=True, max_length=50, verbose_name='屋顶形式')),
                ('dougong_style', models.CharField(blank=True, max_length=50, verbose_name='斗拱样式')),
                ('longitude', models.FloatField(verbose_name='经度')),
                ('latitude', models.FloatField(verbose_name='纬度')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='详细地址')),
                ('introduction', models.TextField(verbose_name='建筑简介')),
                ('historical_value', models.TextField(blank=True, verbose_name='历史价值')),
                ('architectural_features', models.TextField(blank=True, verbose_name='建筑特色')),
                ('liang_sicheng_note', models.TextField(blank=True, verbose_name='梁思成评价')),
                ('image_url', models.CharField(blank=True, max_length=500, verbose_name='图片URL')),
                ('model_3d_url', models.CharField(blank=True, max_length=500, verbose_name='3D模型URL')),
                ('dynasty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.archdynasty', verbose_name='所属朝代')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.archregion', verbose_name='所属地域')),
                ('structure_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.archstructuretype', verbose_name='结构类型')),
            ],
            options={
                'verbose_name': '古建筑',
                'verbose_name_plural': '古建筑',
                'db_table': 'architecture_building',
            },
        ),
        migrations.CreateModel(
            name='ArchUserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dynasty_preference', models.JSONField(default=dict, verbose_name='朝代偏好')),
                ('region_preference', models.JSONField(default=dict, verbose_name='地域偏好')),
                ('type_preference', models.JSONField(default=dict, verbose_name='类型偏好')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.archusers')),
            ],
            options={
                'db_table': 'architecture_user_preference',
            },
        ),
        migrations.CreateModel(
            name='Scenery',
            fields=[
                ('sid', models.IntegerField(primary_key=True, serialize=False)),
                ('sname', models.CharField(blank=True, max_length=45, null=True)),
                ('pid', models.IntegerField(blank=True, null=True)),
                ('did', models.IntegerField()),
                ('label', models.IntegerField(blank=True, null=True)),
                ('introduction', models.CharField(blank=True, max_length=1000, null=True)),
                ('category', models.CharField(blank=True, max_length=45, null=True)),
                ('city', models.CharField(blank=True, max_length=45, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'scenery',
                'unique_together': {('sid', 'did')},
            },
        ),
    ]
