# Generated by Django 6.0.2 on 2026-03-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchitecturalLiterature',
            fields=[
                ('lid', models.IntegerField(primary_key=True, serialize=False)),
                ('lname', models.CharField(max_length=200, verbose_name='文献名称')),
                ('author', models.CharField(max_length=100, verbose_name='作者')),
                ('dynasty', models.CharField(blank=True, max_length=50, verbose_name='朝代/时期')),
                ('publish_year', models.IntegerField(blank=True, null=True, verbose_name='出版年份')),
                ('literature_type', models.CharField(choices=[('ancient', '古代典籍'), ('modern', '现代著作'), ('survey', '调查报告'), ('textbook', '教材'), ('collection', '文集')], max_length=50, verbose_name='文献类型')),
                ('summary', models.TextField(verbose_name='内容摘要')),
                ('key_points', models.TextField(blank=True, verbose_name='核心观点')),
                ('contributions', models.TextField(blank=True, verbose_name='学术贡献')),
                ('publisher', models.CharField(blank=True, max_length=100, verbose_name='出版社')),
                ('edition', models.CharField(blank=True, max_length=50, verbose_name='版本')),
                ('pages', models.IntegerField(blank=True, null=True, verbose_name='页数')),
                ('cover_image', models.CharField(blank=True, max_length=500, verbose_name='封面图片')),
                ('pdf_url', models.CharField(blank=True, max_length=500, verbose_name='PDF链接')),
                ('related_buildings', models.ManyToManyField(blank=True, db_table='architecture_literature_building', to='api.ancientbuilding', verbose_name='相关建筑')),
            ],
            options={
                'verbose_name': '古建筑文献',
                'verbose_name_plural': '古建筑文献',
                'db_table': 'architecture_literature',
            },
        ),
    ]
